const express=require('express')

const userController=require('../controller/userController')
const productController=require('../controller/productController')
const jwtmiddleware = require('../middleware/jwtMiddleware')
const multerConfig = require('../middleware/productMiddleware')
const wishlistController=require('../controller/wishlistController')
const cartController=require('../controller/cartController')
const orderController=require('../controller/orderController')

const router=express.Router()

router.post("/signup",userController.signup)
router.post("/login",userController.login)
router.get("/viewusers",userController.viewUsers)
router.post("/checkmail",userController.verifymail)
router.put("/reset/:id",userController.resetpw)
router.get("/details/:id",userController.details)
router.put("/updateAdmin/:id",userController.update)
router.post("/addproduct",jwtmiddleware,multerConfig.single('cover'),productController.addProduct)
router.get("/viewproduct",productController.viewproduct)
router.get("/getproduct/:id",productController.getproduct)
router.put("/editproduct/:_id",jwtmiddleware,multerConfig.single('cover'),productController.editproduct)
router.get("/fetchfive",productController.fiveproducts)
router.get("/fetchproducts",productController.fetchproducts)
router.get("/fetch/:category",productController.fetch)
router.post("/addwish",wishlistController.add)
router.get("/get/:userId",wishlistController.get)
router.delete("/remove/:id",wishlistController.remove)
router.post("/addcart",cartController.add)
router.get("/fetchcart",cartController.get)
router.delete("/deletefromcart/:id",cartController.removefromcart)
router.put("/increment/:id",cartController.increment)
router.put("/decrement/:id",cartController.decrement)
router.get("/quantity",cartController.totalquantity)
router.get("/price",cartController.totalprice)
router.put("/address/:id",userController.address)
router.delete("/clearcart/:id",cartController.clearcart)
router.post("/addorder",orderController.add)
router.get("/vieworder",orderController.fetchorders)


module.exports=router